language: cpp

compiler:
  - gcc

before_install:
  - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ trusty main universe"
  - sudo apt-get update -qq
  - sudo apt-get install root-system -y

script:
  - source nptool.sh
  - root-config --version
  - cd NPLib
  - cmake ./
  - make install

after_success:
  - npanalysis -h
  - npa
  - cd Example1
  - cmake ./
  - make
  - cd ../Example2
  - cmake ./
  - make

branches:
  only:
    - NPTool.2.dev

os:
  - linux
