sudo: required
dist: trusty
language: cpp

os:
  - linux

compiler:
  - gcc

before_install:
  # Linux
#  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ trusty main universe"; fi
#  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get -qq install root-system; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cd && wget https://www.dropbox.com/s/8hxjkd6twdsv5fi/geant4_install_new.tar.gz; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then tar -xf geant4_install_new.tar.gz; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then source ~/geant4_install/share/Geant4-10.1.2/geant4make/geant4make.sh; fi

  # Dumping stuff for check
  - root-config --version

  # Install NPData needed to run examples suite
  - cd $NPTOOL
  - git clone https://github.com/adrien-matta/NPData

install:

script:
  - cmake --version
  - cd $NPTOOL/NPLib 
  - cmake -GNinja ./
  - ninja install 
  - ./scripts/RootLogon.sh 
  - ./scripts/test/all.sh

after_success:

branches:
  only:
    - NPTool.2.dev

addons:
  apt:
#    sources:
#    - ubuntu-toolchain-r-test
    packages:
    - ninja-build
    - root-system 

#notifications:
#  email:
#    recipients:
#      - support@nptool.org
#    on_success: change
#    on_failure: always
