# Site settings
title: NPTool11
email: a.matta@surrey.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/nptool" # the subpath of your site, e.g. /blog/
url: "http://adrien-matta.github.io" # the base hostname & protocol for your site
github_username: adrien-matta/nptool 

# Build settings
markdown: kramdown
include: [_manual]
source: ./
safe: true
lsi: false
# Defining collection
collections:
  manual:
    output: true
    permalink: /manual/:path/
