# Site settings
title: nptool
email: support@nptool.org
description: > # this means to ignore newlines until "baseurl:"
  nptool, an analysis and simulation framework for nuclear physics experiment based on Root and Geant4.

baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://nptool.org" # the base hostname & protocol for your site
url: "" # use this line when using jekyll serve to preview locally

github_username: adrien-matta/nptool 

# Build settings
markdown: kramdown
include: [_manual]
source: ./ 
safe: true
lsi: false
# Defining collection
collections:
  manual:
    output: true
    permalink: /manual/:path/
    show_in_nav: false
# Making MathJax work
tex2jax: {
  skipTags: ["script","noscript","style","textarea","pre"]
}
